name: prior_list
description: "Organise your tasks by priority and make better use of your time."

publish_to: "none"

version: 1.0.2+5

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.8
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  hugeicons: ^1.0.2
  provider: ^6.1.5+1
  auto_injector: ^2.1.1
  gap: ^3.0.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1
  from_css_color: ^2.0.0
  google_mobile_ads: ^7.0.0
  flutter_svg: ^2.2.3
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.2
  go_router: ^17.1.0

flutter_native_splash:
  image: assets/images/icon_prior_list.png
  color: "#FFFFFF"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/